- type: entity
  id: CrateServiceReplacementElementalLights
  name: elemental lights crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
    - id: BoxElementalLighttube
    - id: BoxElementalLightbulb
