# The job itself
# Escort + ERPer + touchytouchy
- type: job
  id: Escort
  name: job-name-escort
  description: job-description-escort
  playTimeTracker: JobEscort
  whitelisted: true
  startingGear: EscortGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  consoleAdjustable: false
  icon: "JobIconBoxer"
  supervisors: job-supervisors-freebooters-union
  weight: 40
  displayWeight: 3
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  - BlackMarket
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
#    - type: AutoPirate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: DisableSuitSensors
    - type: IsPirate
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierPirate
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraMassageTherapist
  - !type:RpiChatJudgementModifierSpecial
    modsToAdd:
    - rpiChatJudgementModifierMassageTherapist
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant, FreedomImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

#play time tracker
- type: playTimeTracker
  id: JobEscort

- type: entity
  id: SpawnPointEscort
  parent: SpawnPointJobBase
  name: escort spawn point
  suffix: Frontier
  components:
  - type: SpawnPoint
    job_id: Escort
  - type: Sprite
    sprite: Structures/Decoration/banner.rsi
    state: banner-red

- type: startingGear
  id: EscortGear
  equipment:
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
  storage:
    back:
    - EncryptionKeyFreelance
    - ShipVoucherCoyoteEscort
    - ComputerIFFFlatpack

- type: chameleonOutfit
  id: EscortChameleonOutfit
  job: Escort
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef

- type: roleLoadout
  id: JobEscort
  groups:
  - FreelancerFactionHead # LoneStar
  - FreelancerFactionNeck # LoneStar
  - FreelancerFactionJumpsuit # LoneStar
  - MercenaryGloves
  - PilotBackpack
  - FreelancerFactionOuterClothing # LoneStar
  - MercenaryShoes
  - PilotFace
  - MercenaryGlasses
  - MercenaryBelt
  - PilotEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - SmugglerPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorBackpackItems
  - ContractorHandItems
  - ContractorInstruments
  - NFSpeciesSpecific
  canCustomizeName: true # pseudonym?
