# The job itself
# Freelancer + Medic + Crime
- type: job
  id: RipperDoc
  name: job-name-ripperdoc
  description: job-description-ripperdoc
  playTimeTracker: JobRipperDoc
  whitelisted: true
  startingGear: RipperGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  consoleAdjustable: false
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-freebooters-union
  weight: 40
  displayWeight: 3
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  - BlackMarket
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
#    - type: AutoPirate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: DisableSuitSensors
    - type: IsPirate
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierPirate
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraNurse
  - !type:RpiChatJudgementModifierSpecial
    modsToAdd:
    - rpiChatJudgementModifierNurse
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant, EmpImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

#play time tracker
- type: playTimeTracker
  id: JobRipperDoc

- type: entity
  id: SpawnPointRipper
  parent: SpawnPointJobBase
  name: ripper spawn point
  suffix: Frontier
  components:
  - type: SpawnPoint
    job_id: RipperDoc
  - type: Sprite
    sprite: Structures/Decoration/banner.rsi
    state: banner-red

- type: startingGear
  id: RipperGear
  equipment:
    belt: ClothingBeltMedical
    pocket1: BasePirateUplinkPirateCrew
  storage:
    back:
    - EncryptionKeyFreelance
    - EncryptionKeyMedical
    - ComputerIFFFlatpack

- type: chameleonOutfit
  id: RipperDocChameleonOutfit
  job: RipperDoc
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex

- type: roleLoadout
  id: JobRipperDoc
  groups:
  - FreelancerFactionHead # LoneStar
  - FreelancerFactionNeck # LoneStar
  - FreelancerFactionJumpsuit # LoneStar
  - MercenaryGloves
  - PilotBackpack
  - FreelancerFactionOuterClothing # LoneStar
  - MercenaryShoes
  - PilotFace
  - MercenaryGlasses
  - MercenaryBelt
  - PilotEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - SmugglerPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorBackpackItems
  - ContractorHandItems
  - ContractorInstruments
  - NFSpeciesSpecific
  canCustomizeName: true # pseudonym?
